openapi: 3.0.0
info:
  title: Microservice Typescript Template
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000/
    description: Optional server description, e.g. Main (production) server
  - url: http://localhost:3000/
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: Basic
paths:
  /apis/v1/users:
    get:
      tags:
        - Basic
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    number:
                      type: integer
                    name:
                      type: string
                    gender:
                      type: string
  /health:
    get:
      tags:
        - HealthCheck
      summary: Returns Health Of Server.
      description: Returns Health Of Server.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    number:
                      type: integer
                    name:
                      type: string
                    gender:
                      type: string
